#!/bin/sh

DEVICE="untitled"

function load_module() {
  # NOTE: Have to load module before device creation (dynamic alloc major num)
  insmod "$DEVICE.ko"
  MAJOR=`awk "\\$2==\"$DEVICE\" {print \\$1}" /proc/devices`
  echo "MAJOR: ${MAJOR}"
}

case "$1" in
  "start")
    load_module
    ;;
  "stop")
    rmmod "$DEVICE"
    ;;
  "restart")
    rmmod "$DEVICE"
    load_module
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    return 1
    ;;
esac
